remote_theme: pmarsceill/just-the-docs
markdown: kramdown
title: Panduan Hosting
description: DOM Cloud Hosting
baseurl: /
url: https://dok.dom.my.id
google_analytics: "UA-109180894-3"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
