remote_theme: pmarsceill/just-the-docs
markdown: kramdown
title: Panduan DOM Cloud
description: DOM Cloud Hosting Solution Indonesia
baseurl: /
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
